lesson 1
kkazlov/webix-homework pull request #1
Opened 2021-09-23 09:59 UTC by kkazlov

2021-09-23 11:40 UTC, olimed reviewed
1) данные, которые испоьзуются для таблицы, лучше вынести в отдельный файл и потом их импортировать в главный файл
2) лучше разбить конфиг страницы на элементы и создать для них отдельные переменные: 
const header = {...};
const table = {...};
....
это для того, чтобы было лечге изменять какие-то части страницы

2021-09-23 11:40 UTC, olimed commented on webix.js
> +            },
1) можно использовать `view: "toolbar"`
2) можно использовать темы webix: `css: "webix_dark"`

2021-09-23 11:40 UTC, olimed commented on webix.js
> +                            },
это должен быть не кликабельный элемент, используй `view: "template"`

2021-09-23 11:40 UTC, olimed commented on webix.js
> +                        view: "datatable",
скрола по горизонтали не должно быть

2021-09-23 11:40 UTC, olimed commented on webix.js
> +                    <footer>
в данном случае, нет смысла добавлять `<footer>`, так как `template` - это `div` и получается твой `<footer>` имеет обертку `div`

2021-09-23 16:08 UTC, HelgaListopad requested changes

2021-09-23 16:08 UTC, HelgaListopad commented on style.css
> +    border: none;
Бордерами вокруг компонента лучше управлять через свойство `borderless`.

2021-09-23 16:08 UTC, HelgaListopad commented on webix.js
> +                        autowidth: true,
`autowidth` даёт фиксированный размер, который перебивает `gravity`. 
В целом, в `gravity` здесь нет нужды.

2021-09-23 16:08 UTC, HelgaListopad commented on webix.js
> +                    { gravity: 2 },
В таком случае размеры лучше строить иначе
- label c `autowidth`
- spacer (no size)
- button c `autowidth`

Spacer сам растянется на доступное место

2021-09-23 16:08 UTC, HelgaListopad commented on webix.js
> +                        autoheight: false,
false по умолчанию, можно убрать

2021-09-23 16:08 UTC, HelgaListopad commented on webix.js
> +                        gravity: 1,
Единица - значеине для gravity по умолчанию, поэтому можно удалить

2021-09-23 16:29 UTC, kkazlov commented on webix.js
> +            },
done

2021-09-23 16:29 UTC, kkazlov commented on webix.js
> +                            },
done

2021-09-23 16:30 UTC, kkazlov commented on webix.js
> +                        view: "datatable",
done

2021-09-23 16:30 UTC, kkazlov commented on webix.js
> +                    <footer>
done

2021-09-23 16:32 UTC, kkazlov commented on style.css
> +    border: none;
done

2021-09-23 16:38 UTC, kkazlov commented on webix.js
> +                    { gravity: 2 },
done

2021-09-23 16:40 UTC, kkazlov commented on webix.js
> +                        autoheight: false,
done

2021-09-23 16:49 UTC, kkazlov commented on webix.js
> +                        autowidth: true,
done

2021-09-23 16:49 UTC, kkazlov commented on webix.js
> +                        gravity: 1,
done

2021-09-23 17:51 UTC, HelgaListopad commented on webix.js
> +            },
`webix_dark` - это [тёмная тема](https://docs.webix.com/desktop__toolbar.html#darktheme) тулбара, которая также повлияет на вложенные в него кнопки и лэйблы.
У кнопок есть несколько [встроенных стилей](https://docs.webix.com/desktop__button.html#buttontypesandstyles) - они подстроятся под dark, поэтому отпадает нужда стилизовать кнопки, достаточно использовать `webix_transparent`

2021-09-24 05:06 UTC, kkazlov commented on webix.js
> +            },
done

2021-09-24 06:03 UTC, olimed approved these changes

2021-09-24 08:06 UTC, HelgaListopad approved these changes

2021-09-24 08:25 UTC, merged