Lesson5
kkazlov/webix-homework pull request #5
Opened 2021-09-29 07:51 UTC by kkazlov

Lesson5 to review

2021-09-29 12:39 UTC, olimed commented on webix/components/admin.js
> +        } */
не нужный код лучше удалять перед ПР

2021-09-29 12:39 UTC, olimed commented on webix/components/admin.js
> +            $$('adminForm').clearValidation();
можно использовать константу `form`

2021-09-29 12:39 UTC, olimed commented on webix/app.js
> +    $$("adminTable").sync(categoriesDB);
можно в  `adminTable`  просто прописать свойство `data: categoriesDB`

2021-09-29 12:39 UTC, olimed commented on webix/components/datatable.js
> -    },
можно оставить эту схему, только проверять если в `obj` свойство `categoryId` и тогда не использовать событие `onAfterLoad`

2021-09-29 12:39 UTC, olimed commented on webix/components/form.js
> +                myTable.filterByAll();
так как этот код повторяется и не зависит естьли id или нет, то можно это вынести перед `if`

2021-09-29 12:39 UTC, olimed commented on webix/components/form.js
> +            value: 0,
лучше удалить это свойство, так как может быть запись с такой id

2021-09-29 12:39 UTC, olimed commented on webix/components/form.js
> +                $$("formRichSelect").setValue(0);
и тогда тут не нужно будет использовать 0

2021-09-29 12:39 UTC, olimed commented on webix/components/form.js
> +        return value !== 0 && webix.rules.isNotEmpty(value);
и проверка на 0 не нужна будет

2021-09-29 12:39 UTC, olimed commented on webix/app.js
> +    $$("usersList").sync(usersDB, highlightAge);
лучше highlightAge добавить в Datacollection

2021-09-29 16:16 UTC, kkazlov commented on webix/app.js
> +    $$("adminTable").sync(categoriesDB);
done

2021-09-29 16:19 UTC, kkazlov commented on webix/components/datatable.js
> -    },
done

2021-09-29 16:20 UTC, kkazlov commented on webix/components/form.js
> +                myTable.filterByAll();
done

2021-09-29 16:30 UTC, kkazlov commented on webix/components/form.js
> +            value: 0,
done

2021-09-29 16:30 UTC, kkazlov commented on webix/components/form.js
> +                $$("formRichSelect").setValue(0);
done

2021-09-29 16:30 UTC, kkazlov commented on webix/components/form.js
> +        return value !== 0 && webix.rules.isNotEmpty(value);
done

2021-09-29 16:34 UTC, kkazlov commented on webix/app.js
> +    $$("usersList").sync(usersDB, highlightAge);
done

2021-09-29 16:56 UTC, kkazlov commented on webix/components/admin.js
> +            $$('adminForm').clearValidation();
done

2021-09-29 16:57 UTC, olimed commented on webix/components/users-list.js
> +const highlightAge = function() {
Если функция не используется, то ее можно удалить

2021-09-29 16:57 UTC, kkazlov commented on webix/components/admin.js
> +        } */
done

2021-09-29 17:00 UTC, kkazlov commented on webix/components/users-list.js
> +const highlightAge = function() {
done

2021-09-29 17:01 UTC, olimed approved these changes

2021-09-29 17:54 UTC, HelgaListopad commented on webix/components/form.js
> +            value: 0,
Открываю обратно ради одной ремарки: `id` data item'a не может быть задано как `0` (число), `null`, `false`, `NaN`.
Строка `"0"` прокатит, но так тоже лучше не делать во избежание путаницы.

2021-09-29 18:06 UTC, HelgaListopad requested changes

2021-09-29 18:06 UTC, HelgaListopad commented on webix/components/admin.js
> +                    return false;
Промис асинхронный, из него уже не надо ничего возвращать
Если ты захочешь запретить дальнейшую обработку клика, возвращай false из самой функции
```js
"wxi-trash": function (e, id) {
   ...
   return false;
}
```

2021-09-29 18:06 UTC, HelgaListopad commented on webix/components/admin.js
> +                    $$("myTable").filterByAll();
У этой таблицы фильтров нет, так что метод лишний

2021-09-30 04:00 UTC, kkazlov commented on webix/components/admin.js
> +                    return false;
done

2021-09-30 04:00 UTC, kkazlov commented on webix/components/admin.js
> +                    $$("myTable").filterByAll();
done

2021-09-30 04:09 UTC, kkazlov commented on webix/components/form.js
> +            value: 0,
Понял, спасибо за замечание.

2021-09-30 10:34 UTC, HelgaListopad approved these changes

2021-09-30 10:48 UTC, merged